architectury { common(rootProject.enabled_platforms.split(',')) }

dependencies {
    modImplementation "dev.architectury:architectury:$rootProject.architectury_version"
    // Only the Environment annotations may be used from Fabric Loader in common code.
    compileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test { useJUnitPlatform() }
